"""
Constants for the Hybrid Search Service
"""

# Search configuration
DEFAULT_SEARCH_LIMIT = 20
MAX_SEARCH_LIMIT = 100
MIN_RELEVANCE_SCORE = 0.3
DEFAULT_TIMEOUT = 30.0

# Pagination defaults
DEFAULT_PAGE_SIZE = 12
MAX_PAGE_SIZE = 50

# YouTube specific
YOUTUBE_MIN_SUBSCRIBERS = 1000
YOUTUBE_MIN_VIDEO_COUNT = 10

# Scoring weights
EXACT_MATCH_WEIGHT = 1.0
USERNAME_MATCH_WEIGHT = 0.8
FULL_NAME_MATCH_WEIGHT = 0.6
BIO_MATCH_WEIGHT = 0.3
VERIFIED_BONUS = 0.2
HIGH_ENGAGEMENT_BONUS = 0.2
HIGH_FOLLOWERS_BONUS = 0.1

# Synonym limits
MAX_SYNONYMS_PER_CATEGORY = 3

# Database query optimization
BATCH_SIZE = 1000
MAX_QUERY_RESULTS = 10000
